name: trigger_workflow_from_comment
on:
  issue_comment:
    types:
      - created

jobs:
  trigger_workflow:
    permissions:
      actions: write
      checks: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Trigger PR Check Workflow
        run: |
          if [[ ${{ github.event_name }} == 'issue_comment' && ${{ github.event.issue.pull_request }} ]]; then
            # Check if the comment contains a specific trigger phrase
            if [[ $(echo "${{ github.event.comment.body }}" | grep -E '\trigger-pr-check') ]]; then
              echo "Triggering the PR Check workflow..."
              # Trigger the PR Check workflow using repository_dispatch event
              echo "${{ github.repository }}"
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$${{ github.repository }}/actions/workflows/pr_check.yml/dispatches \
                -d '{"ref":"${{ GITHUB_HEAD_REF }}"}'
            else
              echo "Comment does not contain the trigger phrase. Skipping the workflow trigger."
            fi
          else
            echo "Not a pull request comment. Skipping the workflow trigger."
          fi
