name: trigger_workflow_from_comment
on:
  issue_comment:
    types:
      - created

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue_comment.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo A comment on PR ${NUMBER} Test
        env:
          NUMBER: ${{ github.event.issue.number }}
