name: trigger_workflow_from_comment
on:
  issue_comment:
    types:
      - created

jobs:
  trigger_workflow:
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: read
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/trigger-workflow')
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Details from issue_comment
        id: get-workflow-details
        run: |
          input_str="${{ github.event.comment.body }}"
          command_name="/trigger-workflow"

          # Remove the leading ‘\trigger-workflow ’
          command_params=${input_str#$command_name}
          IFS=' ' read -ra args <<< $command_params

          workflow_name=${args[0]}
          echo "workflow_name=${workflow_name}" >> $GITHUB_OUTPUT

          for ((i = 1; i < ${#args[@]}; i++)); do
              arg=${args[i]}
              if [[ $arg == --* ]]; then
                  key=${arg#--}
              else
                  echo "${key}=${arg}" >> $GITHUB_OUTPUT
              fi
          done

      - name: Get PR Details
        id: get-pr-details
        run: | 
          PR_HEAD_BRANCH=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" \
            |jq -r .head.ref)

          echo "pr_head=${PR_HEAD_BRANCH}" >> $GITHUB_OUTPUT

      - name: Trigger PR Check Workflow
        run: |
          echo "Triggering the PR Check workflow..."
          echo "${{steps.get-workflow-details.outputs.workflow_name}}"
          # Trigger the PR Check workflow using repository_dispatch event
          # curl -L \
          #   -X POST \
          #   -H "Accept: application/vnd.github+json" \
          #   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "X-GitHub-Api-Version: 2022-11-28" \
          #   https://api.github.com/repos/${{ github.repository }}/actions/workflows/pr_check.yml/dispatches \
          #   -d '{"ref":"${{ steps.get-pr-details.outputs.pr_head }}"}'

