name: trigger_workflow_from_comment
on:
  issue_comment:
    types:
      - created

jobs:
  trigger_workflow:
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: read
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/trigger-pr-check')
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Details from issue_comment
        id: get-workflow-details-from-comment
        run: |
          input_str=‘\trigger-workflow <Workflow-name> --arg1 2’
          # Remove the leading ‘\trigger-workflow ’
          args=${input_str#*<}
          workflow_name=${args%%>*}
          args=${args#*> }
          # Split the remaining arguments
          for arg in $args; do
              if [[ $arg == --* ]]; then
                  key=${arg#--}
                  declare $key=
              else
                  declare $key=$arg
              fi
          done
          # Output the parsed values
          echo “Workflow Name: $workflow_name”
          echo “Arg1: $arg1"
      - name: Get PR Details
        id: get-pr-details
        run: | 
          PR_HEAD_BRANCH=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" \
            |jq -r .head.ref)

          echo "pr_head=${PR_HEAD_BRANCH}" >> $GITHUB_OUTPUT
      - name: Trigger PR Check Workflow
        run: |
          echo "Triggering the PR Check workflow..."
          # Trigger the PR Check workflow using repository_dispatch event
          # curl -L \
          #   -X POST \
          #   -H "Accept: application/vnd.github+json" \
          #   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "X-GitHub-Api-Version: 2022-11-28" \
          #   https://api.github.com/repos/${{ github.repository }}/actions/workflows/pr_check.yml/dispatches \
          #   -d '{"ref":"${{ steps.get-pr-details.outputs.pr_head }}"}'

